const initClassList = [{
	graySwitch:0,
	picUrl:'/images/merchant/classification_eva@2x.png'
},{
	graySwitch:0,
	picUrl:'/images/merchant/classification_eva@2x.png'
},{
	graySwitch:0,
	picUrl:'/images/merchant/classification_eva@2x.png'
},{
	graySwitch:0,
	picUrl:'/images/merchant/classification_eva@2x.png'
},{
	graySwitch:0,
	picUrl:'/images/merchant/classification_eva@2x.png'
},{
	graySwitch:0,
	picUrl:'/images/merchant/classification_eva@2x.png'
},{
	graySwitch:0,
	picUrl:'/images/merchant/classification_eva@2x.png'
},{
	graySwitch:0,
	picUrl:'/images/merchant/classification_eva@2x.png'
}];
const imgUrls = [{
	  	picUrl:'/images/merchant/advertisement.png',
    },{
	  	picUrl:'/images/merchant/advertisement.png',
    },{
	  	picUrl:'/images/merchant/advertisement.png',
    },{
	  	picUrl:'/images/merchant/advertisement.png',
    },{
	  	picUrl:'/images/merchant/advertisement.png',
    },];
const merchantFeature = [{
		feature:'可视餐厅',
		isSelect:false
	},{
		feature:'跨天预订',
		isSelect:false
	},{
		feature:'点评高分',
		isSelect:false
	}];
const merchantActive = [{
		active:'首单立减',
		isSelect:false
	},{
		active:'满减优惠',
		isSelect:false
	},{
		active:'满赠优惠',
		isSelect:false
	},{
		active:'折扣商品',
		isSelect:false
	}];
module.exports = {
	initClassList,
	imgUrls,
	merchantFeature,
	merchantActive
};