const initClassList = [{
	graySwitch:0,
	picUrl:'/images/merchant/classification_eva@2x.png'
},{
	graySwitch:0,
	picUrl:'/images/merchant/classification_eva@2x.png'
},{
	graySwitch:0,
	picUrl:'/images/merchant/classification_eva@2x.png'
},{
	graySwitch:0,
	picUrl:'/images/merchant/classification_eva@2x.png'
},{
	graySwitch:0,
	picUrl:'/images/merchant/classification_eva@2x.png'
},{
	graySwitch:0,
	picUrl:'/images/merchant/classification_eva@2x.png'
},{
	graySwitch:0,
	picUrl:'/images/merchant/classification_eva@2x.png'
},{
	graySwitch:0,
	picUrl:'/images/merchant/classification_eva@2x.png'
}];
const imgUrls = [{
  	picUrl:'/images/merchant/advertisement.png',
  },{
  	picUrl:'/images/merchant/advertisement.png',
  },{
  	picUrl:'/images/merchant/advertisement.png',
  },{
  	picUrl:'/images/merchant/advertisement.png',
  },{
  	picUrl:'/images/merchant/advertisement.png',
  },]
module.exports = {
	initClassList:initClassList,
	imgUrls:imgUrls
}